### ISSUE TITLE
ECONNREFUSED error 

### ISSUE THREAD

**Issue by niara100** [Lavaclient/lavaclient#17]
about a second after the bot starts the console gets spammed with this error message
im not sure why this is occuring.

`main ran into an error Error: connect ECONNREFUSED 127.0.0.1:2334
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2334
}`

**Comment by IamGoDsoIamBest** [comment]
Make sure your lavalink is running in background and check the port properly

**Comment by MeLike2D** [comment]
Yeah, like @IamGoDsoIamBest make sure you have lavalink running and you gave lavaclient the correct password, hostname, and port.
