### ISSUE TITLE
Weirdly behaving queue

### ISSUE THREAD

**Issue by Heges69** [lavaclient/lavaclient#84]
## Describe the bug

Hello, I am currently using lavaclient in production in bot with 4000 servers and I am having issues when using any sharder, that uses clusters(I tried kurasuta and discord-hybrid-sharding), the bot works fine, but after a random time(few hours to 1 day), it starts to glitch, when skipping a song it throws an error `TypeError: Cannot read properties of undefined (reading 'title')` and when you try to queue another song, it starts to play the song you queued and skips the last one.
I am also using `@lavaclient/queue` and `@lavaclient/spotify`

### To Reproduce

Use kurasuta for example and let the bot run for a few hours to 1 day.

### Expected behavior

The bot should work as it should.

## Environment

**nodejs versions**: 18.2.0 and 16.6.2
**lavalink version**: 3.4
**lavaclient version**: 4.0.8

**Comment by Heges69** [comment]
Okay, I have made my own queue handler and it works.

**Comment by melike2d** [comment]
Sorry to have missed this, lavaclient plugins are on the back-burner as of now. 

Feel free to PR @lavaclient/queue with any changes as you see fit.
