### ISSUE TITLE
Lavaclient v5

### ISSUE THREAD

**Issue by viztea** [lavaclient/lavaclient#86]

**Comment by melike2d** [comment]
Lavaclient v5 introduces 3 new packages to the NPM registry:
- `lavalink-protocol` @effect/schema validation for the lavalink protocol
- `lavalink-api-client` a type-safe api client for lavalink built on-top of `protocol`
- `lavalink-ws-client` a type-safe ws client for lavalink built on-top of `api-client` and `protocol`

This means `@lavaclient/types` will be retired when v5 releases.
