### ISSUE TITLE
bug: position value reverted back to lastPosition when paused

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [lavaclient/lavaclient#88]
## Describe the bug

When `player.pause()` is called, `position` value reverted back to `lastPosition` for few milliseconds

### To Reproduce

```ts
// show current position and lastPosition every second
setInterval(() => {
  const { position, lastPosition } = player;
  console.log("tick", { position, lastPosition });
}, 1000);

// log value before pause
console.log("before", {
  position: player.position,
  lastPosition: player.lastPosition,
});

await player.pause();

// log value after paused
console.log("after", {
  position: player.position,
  lastPosition: player.lastPosition,
});
```

Output:
```js
tick { position: 967, lastPosition: 0 }
tick { position: 1976, lastPosition: 0 }
tick { position: 2986, lastPosition: 0 }
tick { position: 3992, lastPosition: 0 }
tick { position: 4875, lastPosition: 4840 }
before { position: 5286, lastPosition: 4840 }
after { position: 4840, lastPosition: 4840 } // position value reverted back to lastPosition value
tick { position: 5280, lastPosition: 5280 } // fixed here
tick { position: 5280, lastPosition: 5280 }
tick { position: 5280, lastPosition: 5280 }
tick { position: 5280, lastPosition: 5280 }
```

I have to add some delay before logging `after` to get the accurate `position` value

```ts
// log value before pause
console.log("before", {
  position: player.position,
  lastPosition: player.lastPosition,
});

await player.pause();
await new Promise((r) => setTimeout(r, 1000));

// log value after paused
console.log("after", {
  position: player.position,
  lastPosition: player.lastPosition,
});
```

Output:
```js
tick { position: 975, lastPosition: 0 }
tick { position: 1984, lastPosition: 0 }
tick { position: 2999, lastPosition: 0 }
tick { position: 4009, lastPosition: 0 }
before { position: 4806, lastPosition: 0 }
tick { position: 4760, lastPosition: 4760 }
after { position: 4760, lastPosition: 4760 }
tick { position: 4760, lastPosition: 4760 }
tick { position: 4760, lastPosition: 4760 }
tick { position: 4760, lastPosition: 4760 }
tick { position: 4760, lastPosition: 4760 }
```

### Expected behavior

`position` value shouldn't revert back to `lastPosition` value when player paused.

## Environment

- **nodejs version**: `v16.16.0`
- **lavalink version**: `3.7` (docker)
- **lavaclient version**: `4.1.1`

**Comment by SerenModz21** [comment]
The code provided, is that what you use? Lavaclient's player class does not have an `audioPlayer` property.

**Comment by SuspiciousLookingOwl** [comment]
Whoops forgot to change it, it's from the code I use, `player.audioPlayer` is Lavaclient's player (from `lavalink.createPlayer(...)`)

**Comment by SerenModz21** [comment]
could u listen to the debug event and show us what is shown?

**Comment by melike2d** [comment]
Lavaclient returns `lastPosition` while paused because the position would appear to advance even though it actually isn't.

see https://github.com/lavaclient/lavaclient/blob/master/src/lib/Player.ts#L69-L71

I could just store when the player is paused but that's quite sloppy imo 🤷🏼

**Comment by SuspiciousLookingOwl** [comment]
Yep I just noticed that after learning more about Lavalink, I have a use case that requires quite accurate position time, so I just decrease the `playerUpdateInterval` value on Lavalink config. Disregard this issue 😄

**Comment by melike2d** [comment]
All good :)
